### ISSUE TITLE
Content-Range header reporting incorrectly?

### ISSUE THREAD

**Issue by scottbuckley** [pomle/php-serveFilePartial#1]
Hi there. I'm using this function for a php version of subsonic I have been developing. It is a life-saver - I didn't want to have to write partial file response (for Safari) from scratch.

However, I have noticed that the 'audio' tag in Safari seems to 'test' a server's partial-file response by always asking first for bytes 0-1 of a track before 'trusting' the partial file service. Attached is a screenshot of such a request header.
![screen shot 2014-04-28 at 2 01 48 am](https://cloud.githubusercontent.com/assets/2231328/2811571/a57dcec6-ce25-11e3-9035-017679829a0e.png)

This function seems to return a content-range that is inappropriate. Attached is a screenshot of a return header.
![screen shot 2014-04-28 at 2 01 57 am](https://cloud.githubusercontent.com/assets/2231328/2811575/bd2b8e64-ce25-11e3-8c73-1c662ebd9f7c.png)

Changing ServeFilePartial.inc.php:38 to remove the -1 seems to fix this issue, and allow Safari to 'trust' the partial file service. This is necessary for audio tags to allow a user to skip through a file.

There is a comment on this line which says that you reduce by one because the range is zero-based, which I assume is talking about how bytes 0-0 should be one byte. However, if the server is asking for the range 0-1, then they are talking about two bytes, and you return 0 instead of two there. I didn't put a whole heap of thought into this; I just removed the -1 and it started working :)

**Comment by ht2** [comment]
So, we have had a very similar issue with Safari, but with MP4s instead. It wasn't enough to remove the "- 1" because there is an error where the byeOffset is taken off the byteLength. This shouldn't be the case, instead the second value of the Content-Range header should be the value of $match[2], but the $byteLength needs to be -1!

Anyway, here's a gist of a working version of the code for us:
https://gist.github.com/ht2/97fc31c204310f9194e1

**Comment by pomle** [comment]
Thanks for taking time with this!

Sorry I have not responded. I have honestly not seen the notifications.

If you have a pull-request, I'd be happy to accept!
